version: 2
machine:
  node:
    version: 10.9.0
jobs:
  ################################################################################
  test_main_client:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1
      - run:
          name: install-deps
          command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint -- --project=main-client --format=stylish
      - run:
          name: test
          command: npm run test -- --project=main-client -c=ci --progress=false --code-coverage
      - store_artifacts:
          path: coverage
      - run:
          name: jit build
          command: npm run build -- --project=main-client --progress=false
  ################################################################################
  e2e_main_client:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1
      - run:
          name: install-deps
          command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: e2e
          command: npm run e2e -- --project=main-client-e2e-cypress --headless
      - store_artifacts:
          path: dist/out-tsc/apps/main-client-e2e
  ################################################################################
  test_functions:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys: function-node-v1-{{ .Branch }}-{{ checksum "./functions/package-lock.json" }}
      - run:
          working_directory: ./functions
          name: install-deps
          command: npm ci
      - save_cache:
          key: function-node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          working_directory: ./functions
          name: build
          command: npm run build
  ################################################################################
  build_main_client:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1
      - run:
          name: install-deps
          command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build -- --project=main-client -c=production --progress=false
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package.json
            - firebase.json
            - .firebaserc
            - firebase.json
  ################################################################################
  deploy_main_client:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: install firebase cli
          command: npm install firebase-tools
      - run:
          name: deploy to firebase
          command: npx firebase deploy --token=$FIREBASE_TOKEN --only=hosting
  ################################################################################
workflows:
  version: 2
  ################################################################################
  test_and_build_overnight:
    triggers:
      - schedule:
          # 10pm PST
          cron: '0 05 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - test_main_client
      - e2e_main_client
      - test_functions
      - build_main_client:
          requires:
            - test_main_client
  ################################################################################
  test_and_deploy:
    jobs:
      - test_main_client
      - e2e_main_client
      - build_main_client:
          requires:
            - test_main_client
      - deploy_main_client:
          filters:
            branches:
              only:
                - master
          requires:
            - build_main_client
            - e2e_main_client
      - test_functions
